### ISSUE TITLE
Radix.java:120) - Unable to start -- can't connect to remote host (172.18.0.2):

### ISSUE THREAD

**Issue by Meai** [radixdlt/radixdlt-core#275]
```
pc@linux-a7b0:~/workarea/radix/my-radixexample/radixdlt-core> ./gradlew deb4docker
<-------------> 0% CONFIGURING [2s]
> root project > Resolve dependencies of detachedConfiguration3 > me.champeau.gradle.jmh.gradle.plugin-0.5.1.> root project > Resolve dependencies of detachedConfiguration3 > me.champeau.gradle.jmh.gradle.plugi
> Task :faucet-service:versionFile
Base tags : []

> Task :radixdlt:versionFile
Base tags : []

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

pc@linux-a7b0:~/workarea/radix/my-radixexample/radixdlt-core> sudo docker-compose -f docker/single-node.yml up --build
[sudo] password for root: 
WARNING: The RADIXDLT_UNIVERSE variable is not set. Defaulting to a blank string.
WARNING: The RADIXDLT_UNIVERSE_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The RADIXDLT_UNIVERSE_PRIVKEY variable is not set. Defaulting to a blank string.
Creating network "docker_single_node" with the default driver
[...docker build stuff...]
faucet_1  | wget: can't connect to remote host (172.18.0.2): Connection refused
core_1    | # 2020-11-22T08:49:19,944 [FATAL/Radix/main] (Radix.java:120) - Unable to start
core_1    | com.google.inject.ProvisionException: Unable to provision, see the following errors:
core_1    | 
core_1    | 1) Error in custom provider, java.lang.IllegalStateException: Error while deserialising universe
core_1    |   at com.radixdlt.CheckpointModule.universe(Unknown Source)
core_1    |   while locating com.radixdlt.universe.Universe
core_1    |     for the 2nd parameter of com.radixdlt.network.transport.udp.UDPTransportModule.natHandlerProvider(Unknown Source)
core_1    |   at com.radixdlt.network.transport.udp.UDPTransportModule.natHandlerProvider(Unknown Source)
core_1    |   while locating com.radixdlt.network.transport.udp.NatHandler
core_1    |     for the 5th parameter of com.radixdlt.network.transport.udp.NettyUDPTransportImpl.<init>(Unknown Source)
core_1    |   while locating com.radixdlt.network.transport.udp.NettyUDPTransportImpl
core_1    |   while locating com.radixdlt.network.transport.Transport annotated with @com.google.inject.internal.Element(setName=,uniqueId=11, type=MULTIBINDER, keyType=)
[...long stacktrace...]
Attaching to docker_faucet_1, docker_core_1
faucet_1  | Waiting for http://core:8080 to become ready ...
faucet_1  | wget: can't connect to remote host (172.18.0.2): Connection refused
core_1    | + find /usr -type f -name java -exec setfattr -n user.pax.flags -v em {} ;
core_1    | + env
core_1    | + sort
core_1    | HOME=/root
core_1    | HOSTNAME=fb561b744e25
faucet_1  | wget: bad address 'core:8080'
faucet_1  | wget: bad address 'core:8080'
faucet_1  | wget: bad address 'core:8080'
faucet_1  | wget: bad address 'core:8080'
```

**Comment by lfeagan** [comment]
Without going into a bunch of details, take a look at `radixdlt-core/docker/scripts/rundocker.sh` and notice how line 20 calls the gradle task `generateDevUniverse`. You used to basically be able to ignore the universe configuration, but now you need a universe that has atoms with particle for registering the validators and giving them an initial stake so things can be bootstrapped. This gradle task calls GenerateUniverses.java, which you can checkout to understand the options available.

**Comment by clstrfsck** [comment]
@Meai , oof, yes.  I think I see the underlying problem — our README.md hasn't been updated with the new startup process.

We will for sure get this sorted for the next release — thanks for raising the issue.

I think there are a couple of things that it highlights:

1. We are avoiding, wherever practical, committing private keys (including test keys), into repos.
2. Because we have now implemented PoS, we need to have an initial validator set identified by pubkey in the universe, and the actual nodes themselves need to be able to sign messages with the corresponding privkeys.  Because of (1) above, we are generating the keys and universe at launch time.
3. Currently we have no support in the launch scripts for folks that need to use `sudo` with `docker-compose`, so this needs adding.  It would be possible to run the startup script with `sudo`, but that would result in build artifacts being owned by `root` which is not ideal.

In the meantime, the suggestion by @lfeagan is the way to go.  Have a look at `radixdlt-core/docker/scripts/rundocker.sh` — I expect the easiest way to make that work for your use case would be to edit the script to change the `docker-compose` part to `sudo docker-compose`.

**Comment by clstrfsck** [comment]
PR #296

**Comment by Meai** [comment]
@clstrfsck maybe I'm missing something obvious here but your command line example doesnt work for me. Based on your information I changed it so it works for me but maybe you could clarify it further so the readme example works:

```
pc@linux-a7b0:~/workarea/radix/my-radixexample/radixdlt-core> DOCKER_COMPOSE_LAUNCH="sudo -E docker-compose" ./docker/scripts/rundocker.sh 1

> Task :faucet-service:versionFile
[versioning] WARNING - the working copy has unstaged or uncommitted changes.

> Task :radixdlt:versionFile
[versioning] WARNING - the working copy has unstaged or uncommitted changes.

> Task :radixdlt:deb4docker
Deleted conflicting deb package: radixdlt_1.0~beta.20~rc~1.0~beta.21~SNAPSHOT_all.deb ...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
17 actionable tasks: 10 executed, 7 up-to-date
./docker/scripts/rundocker.sh: line 25: -f: command not found
```

**Comment by clstrfsck** [comment]
@Meai maybe it is a difference in the shells we are using.  Which OS and shell/version are you using?

For completeness, I've tested this on MacOS (10.15.7) with bash (3.2.57), but perhaps if you are on MacOS you are now using zsh?
